routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('app');
});

Auth::routes(['register' => false]);

Route::group(['middleware' => 'auth'], function () {
    Route::resource('transactions', 'TransactionsController');
});

app/Transaction.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * Transactin model
 *
 * @property      string $date
 * @property      int $amount
 * @property      string description
 * @property      bool $in_out
 * @property      int $owner_id
 * @property      User|User[] $owner
 * @property-read string $type
 * @property-read string $amount_string
 */
class Transaction extends Model
{
    /**
     * Fillable
     */
    protected $fillable = ['date','amount','description','in_out','owner_id'];

    /**
     * Type attribute.
     *
     * @return string
     */
    public function getTypeAttribute()
    {
        return $this->in_out ? 'Earning' : 'Expense';
    }

    /**
     * The amount_string attribute
     *
     * @return string
     */
    public function getAmountStringAttribute()
    {
        $string = number_format($this->amount);

        if (!$this->in_out) {
            $string = '- '.$string;
        }

        return $string;
    }

    public function getDateOnlyAttribute()
    {
        return substr($this->date, -2);
    }

    public function owner()
    {
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get user transactions history
     *
     * @return HasMany
     */
    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TransactionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Transactions\CreateRequest;
use App\Http\Requests\Transactions\UpdateRequest;
use App\Transaction;
use Illuminate\Http\Request;

class TransactionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param \Illuminate\Http\Request $request Request instance
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index(Request $request)
    {
        /* @var Transaction[] $data Transactions collection */
        $data = Transaction::where('owner_id', $request->user()->id)->get();

        $sumary = (object) [
            'earning' => 0,
            'expense' => 0,
            'balance' => 0,
        ];

        foreach ($data as $row) {
            if ($row->in_out) {
                $sumary->earning += $row->amount;
            } else {
                $sumary->expense += $row->amount;
            }
        }

        $sumary->balance = $sumary->earning - $sumary->expense;

        return view('transactions.index', compact('data', 'sumary'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('transactions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateRequest $transaction Transaction create request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateRequest $transaction)
    {
        $message = $transaction->save()
            ? 'New data created'
            : 'Failed to create new data';

        return redirect()->route('transactions.index')->with('message', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param Transaction $transaction Transaction instance
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function show(Transaction $transaction)
    {
        return $this->edit($transaction);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Transaction $transaction Transaction instance
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function edit(Transaction $transaction)
    {
        return view('transactions.edit', compact('transaction'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRequest $request     Transaction update request
     * @param Transaction   $transaction Transaction instance
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateRequest $request, Transaction $transaction)
    {
        $message = $request->update($transaction)
            ? 'Data saved'
            : 'Failed to save data';

        return redirect()->route('transactions.index')->with('message', $message);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Transaction $transaction Transaction instance.
     *
     * @return array Json response
     */
    public function destroy(Transaction $transaction)
    {
        $this->authorize('delete', $transaction);

        $redirect = route('transactions.index');
        $message = $transaction->delete()
            ? 'Data deleted'
            : 'Failed to delete the data';

        return compact('message', 'redirect');
    }
}

resources/views/app.blade.php
@extends('layouts.base')

@section('content')
    <p>Hello World</p>
@endsection

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="antialiased text-gray-900 leading-snug">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Dompet</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        <link href="{{ mix('css/app.css') }}" rel="stylesheet">

        <meta name="csrf-token" content="{{ csrf_token() }}">
    </head>
    <body class="min-h-screen">
        <div id="app" class="min-h-screen">
            <header class="border-b border-gray-300 z-100 h-12 w-full mb-4">
                <div class="container mx-auto flex">
                    <a class="w-1/6 text-xl leading-normal font-bold block py-2" href="#">Acme</a>
                    <div class="flex flex-grow py-3">
                        <a href="{{ route('transactions.index') }}">Transactions</a>
                    </div>
                </div>
            </header>

            <main class="w-full">
                <div class="container mx-auto">
                    @yield('content')
                </div>
            </main>
        </div>

        <script src="{{ mix('js/app.js') }}"></script>
    </body>
</html>

resources/views/transactions/create.blade.php
@extends('layouts.base')

@section('content')

    <form action="{{ route('transactions.store') }}" method="POST">
        @csrf

        <div class="flex py-2">
            <label class="w-1/6 text-gray-600" for="description">Description</label>
            <input class="flex flex-grow px-2 py-1 rounded border" id="description" name="description" type="text" value="{{ old('description') }}">
        </div>

        <div class="flex py-2">
            <label class="w-1/6 text-gray-600" for="amount">Amount</label>
            <input class="flex-grow px-2 py-1 rounded border" id="amount" name="amount" type="number" value="{{ old('amount') }}">
        </div>

        <div class="flex py-2">
            <label class="w-1/6 text-gray-600" for="date">Date</label>
            <input class="flex-grow px-2 py-1 rounded border" id="date" name="date" type="date" value="{{ old('date', date('Y-m-d')) }}">
        </div>

        <div class="flex py-2">
            <label class="w-1/6 text-gray-600">Type</label>
            <div class="flex-grow">
                <label for="income">
                    <input class="px-2 py-1 rounded border" id="income" name="in_out" value="1" type="radio" {{ old('in_out') === 1 ? 'checked' : '' }}> Income
                </label>
                <label for="outcome">
                    <input class="px-2 py-1 rounded border" id="outcome" name="in_out" value="0" type="radio" {{ old('in_out') === 0 ? 'checked' : '' }}> Outcome
                </label>
            </div>
        </div>

        <div class="flex py-4 mt-4 border-t border-400">
            <button type="submit" class="text-white px-4 py-2 bg-blue-600 rounded">Submit</button>
        </div>
    </form>

@endsection

resources/views/transactions/edit.blade.php
@extends('layouts.base')

@section('content')

    <form action="{{ route('transactions.update', ['transaction' => $transaction]) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="flex py-2">
            <label class="w-1/6 text-gray-600" for="description">Description</label>
            <input class="flex flex-grow px-2 py-1 rounded border" id="description" name="description" type="text" value="{{ $transaction->description }}">
        </div>

        <div class="flex py-2">
            <label class="w-1/6 text-gray-600" for="amount">Amount</label>
            <input class="flex-grow px-2 py-1 rounded border" id="amount" name="amount" type="number" value="{{ $transaction->amount }}">
        </div>

        <div class="flex py-2">
            <label class="w-1/6 text-gray-600" for="date">Date</label>
            <input class="flex-grow px-2 py-1 rounded border" id="date" name="date" type="date" value="{{ $transaction->date }}">
        </div>

        <div class="flex py-2">
            <label class="w-1/6 text-gray-600">Type</label>
            <div class="flex-grow">
                <label for="income">
                    <input class="px-2 py-1 rounded border" id="income" name="in_out" value="1" type="radio" {{ !$transaction->in_out ? 'checked' : ''  }}> Income
                </label>
                <label for="outcome">
                    <input class="px-2 py-1 rounded border" id="outcome" name="in_out" value="0" type="radio" {{ $transaction->in_out ? 'checked' : ''  }}> Outcome
                </label>
            </div>
        </div>

        <div class="flex py-4 mt-4 border-t border-400">
            <button type="submit" class="text-white px-4 py-2 bg-blue-600 rounded">Update</button>
        </div>
    </form>

@endsection

resources/views/transactions/index.blade.php
@extends('layouts.base')

@section('content')

    <header class="w-full block py-6">
        <a class="px-6 py-2 rounded bg-blue-700 text-white" href="{{ route('transactions.create') }}">Create</a>
    </header>

    <table class="table-auto w-full pt-10">
        <thead>
            <tr>
                <th class="py-2 px-2 w-px">#</th>
                <th class="py-2 px-2 w-px">Date</th>
                <th class="py-2 px-2">Description</th>
                <th class="py-2 px-2 w-1/12">Amount</th>
                <th class="py-2 px-2 w-1/12">Action</th>
            </tr>
        </thead>

        <tbody>
            @foreach($data as $i => $row)
            @php
                $groups = $data->where('date_only', $row->date_only);
                $first = $groups->first();
                $count = $groups->count();
            @endphp
            <tr>
                <td class="border px-2 py-2 text-center">{{ $i + 1 }}</td>
                @if($first->id == $row->id)
                    <td rowspan="{{ $count }}" class="border px-2 py-2 text-center">{{ $row->date_only }}</td>
                @endif
                <td class="border px-2 py-2">{{ $row->description }}</td>
                <td class="border px-2 py-2 text-right">{{ $row->amount_string }}</td>
                <td class="border px-2 py-2 text-center">
                    <a class="btn-edit" href="{{ route('transactions.edit', ['transaction' => $row->id]) }}">Edit</a>
                    <a class="btn-delete" data-desc="{{ $row->description }}" href="{{ route('transactions.destroy', ['transaction' => $row->id]) }}">Delete</a>
                </td>
            </tr>
            @endforeach
            <tr>
                <td colspan="5">&nbsp;</td>
            </tr>
            <tr>
                <td class="border px-2 py-2 text-right" colspan="3">Total Earning</td>
                <td class="border px-2 py-2 text-right">{{ $sumary->earning }}</td>
                <td class="border px-2 py-2">&nbsp;</td>
            </tr>
            <tr>
                <td class="border px-2 py-2 text-right" colspan="3">Total Expense</td>
                <td class="border px-2 py-2 text-right">{{ $sumary->expense }}</td>
                <td class="border px-2 py-2">&nbsp;</td>
            </tr>
            <tr>
                <td class="border px-2 py-2 text-right" colspan="3">Current Balance</td>
                <td class="border px-2 py-2 text-right">{{ $sumary->balance }}</td>
                <td class="border px-2 py-2">&nbsp;</td>
            </tr>
        </tbody>
    </table>

@endsection